name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    #environment: 
    #  name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          #template: terminal
          #plugin_isocalendar: yes
          #plugin_isocalendar_duration: full-year # Display full year instead of half year
          #plugin_habits: yes
          plugin_leetcode: yes
          plugin_leetcode_user: rogervdo
          plugin_achievements: yes
          plugin_achievements_display: compact   # Use compact display
